spring:
  application:
    name: monitor-forno

  datasource:
    url: jdbc:postgresql://localhost:5432/forno_monitor
    username: postgres
    password: tsX*WD7AMthXu8r^6fzs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: 96FSe74HoFk7gfxIw8KHcEk8chlZ0dbpkxzQnnYkriw=
  expiration: 86400000